# Employee Service specific configuration
# This file contains settings specific to employee-service

spring:
  application:
    name: employee-service

  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:/db/migration
    table: flyway_schema_history_employees
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Management endpoints for runtime refresh
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    refresh:
      enabled: true
