spring:
  application:
    name: product-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      enabled: true
      fail-fast: true

  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes in milliseconds
      cache-null-values: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Management endpoints for runtime refresh
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    refresh:
      enabled: true
